apiVersion: v1
kind: Pod
metadata:
  labels:
    app: centos-pod
  name: centos-pod
  namespace: default
spec:
  nodeSelector:
    kubernetes.io/hostname: gke-cluster-1-default-pool-d8b544e3-0nz8
  containers:
  - image: centos
    name: centos
    stdin: true
    tty: true
