apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-rs
  labels:
    app: mysql-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-rs-pod
  template:
    metadata:
      labels:
        app: mysql-rs-pod
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-creds
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-creds
              key: db_name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-creds
              key: username
        livenessProbe:
          tcpSocket:
            port: 3306
        ports:
        - containerPort: 3306

