apiVersion: v1
kind: ResourceQuota
metadata:
  name: objects-quota
spec:
  hard:
    count/deployments.apps: 20
    count/replicasets.apps: 100
    count/statefulsets.apps: 20
    count/jobs.batch: 100
    count/cronjobs.batch: 5
    replicationcontrollers: 10
    pods: 500
    secrets: 500
    configmaps: 500
    persistentvolumeclaims: 100
    services: 100
    services.loadbalancers: 10  

