apiVersion: v1
kind: Pod
metadata:
  labels:
    run: {{ .Release.Name }}
  name: {{ .Release.Name }}-pod
spec:
  containers:
  - image: {{ .Values.image }}:{{ .Values.tag }}
    name: {{ .Values.image }}
    ports:
    - containerPort: {{ .Values.port }} 
