apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{ .Release.Name }}-svc
  name: {{ .Release.Name }}-svc
spec:
  ports:
  - port: {{ .Values.port }}
    protocol: TCP
    targetPort: {{ .Values.port }}
  selector:
    run: {{ .Release.Name }}
  type: NodePort
