apiVersion: v1
kind: Pod
metadata:
  labels:
    app: {{ .Release.Name }}-pod
  name: {{ .Release.Name }}-pod
spec:
  containers:
  - image: {{ .Values.image }}:{{ .Values.tag }}
    name: {{ .Values.image }}
    ports:
    - containerPort: {{ .Values.port }}
      protocol: TCP
      name: http

