apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  ports:
  - port: {{ .Values.port }}
    protocol: {{ .Values.protocol }}
    targetPort: {{ .Values.targetport }}
  selector:
    app: {{ .Release.Name }}-deploy
  type: {{ .Values.servicetype }}
