apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ngins-deploy
  annotations:
    kubernetes.io/change-cause: "Downgrade to v1.20"
  name: ngins-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngins-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: ngins-deploy
    spec:
      containers:
      - image: nginx:1.20
        name: nginx
