apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    volume: db-pv
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  nfs:
    server: 165.227.203.115
    path: /share

